name:                unfog
version:             1.0.0
github:              "soywod/unfog"
license:             BSD3
author:              "soywod"
maintainer:          "clement.douin@posteo.net"
copyright:           "2019-2020 Clément DOUIN"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Minimalist task & time manager.
category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/soywod/unfog#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - base-compat
  - bytestring
  - containers
  - directory
  - hspec
  - optparse-applicative
  - process
  - random
  - time
  - uuid

executables:
  unfog:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O3
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - unfog

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies:
      - hspec
      - time
      - unfog
