name:                unfog
version:             0.2.1
github:              "unfog-io/unfog-cli"
license:             BSD3
author:              "Clément DOUIN"
maintainer:          "clement.douin@posteo.net"
copyright:           "2019 Clément DOUIN"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A simple task and time manager.
category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/unfog-io/unfog-cli#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - directory
  - time
  - boxes
  - human-readable-duration
  - aeson
  - bytestring
  - base-compat

executables:
  unfog:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    dependencies:
    - unfog
    - time

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies:
      - unfog
      - time
